[package]
name = "csimdv"
version = "0.1.0"
edition = "2024"

[[bench]]
path = "benches/benchmarks.rs"
name = "benchmarks"
harness = false


[[bench]]
path = "benches/movemask_emul.rs"
name = "movemask"
harness = false

[[bench]]
path = "benches/deserialize.rs"
name = "deserialize"
harness = false

[dev-dependencies]
criterion = "0.8.2"
simd-csv = "0.10.3"
tempfile = "3.3.0"
csv = "1.4.0"
rand = "0.10.2"

[dependencies]
libc = "0.2"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
memchr = "2.8.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = true
strip = false

[lib]
bench = false
