[package]
name = "csimdv"
version = "0.1.0"
edition = "2024"

[[bench]]
path = "benches/benchmarks.rs"
name = "benchmarks"
harness = false

[dev-dependencies]
criterion = "0.8.2"
simd-csv = "0.10.3"
tempfile = "3.3.0"

[dependencies]
memmap2 = "0.9.11"
libc = "0.2.185"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = true
strip = false

[lib]
bench = false
